### ISSUE TITLE
Ошибки FunctionalSwift и MoneyAuth

### ISSUE THREAD

**Issue by docokha** [yoomoney/yookassa-payments-swift#102]
Доброго времени суток!

При попытке импорта библиотеки возникает следующие две ошибки:

`Compiling for iOS 10.0, but module 'FunctionalSwift' has a minimum deployment target of iOS 12.0: /Users/User/Library/Developer/Xcode/DerivedData/PD-bdnqimrypdaftkdtbduaoeaevhee/Build/Products/Debug-iphonesimulator/FunctionalSwift/FunctionalSwift.framework/Modules/FunctionalSwift.swiftmodule/x86_64-apple-ios-simulator.swiftmodule`

`Failed to build module 'MoneyAuth' from its module interface; the compiler that produced it, 'Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)'`

Podfile:
```
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/yoomoney-tech/cocoa-pod-specs.git'

platform :ios, '13.0'
use_frameworks!
target 'PD' do
  pod 'YooKassaPayments',
    :git => 'https://github.com/yoomoney/yookassa-payments-swift.git',
    :tag => '5.2.0'

end
```

Xcode version 12.4

Версия приложения 13.0+

Буду очень благодарен за помощь!

**Comment by pavlof01** [comment]
такая-же проблема

**Comment by oltv00** [comment]
Привет!

Попробуйте собрать [последнюю версию 5.3.0](https://github.com/yoomoney/yookassa-payments-swift/releases/tag/5.3.0).

**Comment by kirsantov** [comment]
Compiling for iOS 10.0, but module 'FunctionalSwift' has a minimum deployment target of iOS 11.0

Failed to build module 'MoneyAuth' from its module interface; the compiler that produced it, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)'

` pod 'YooKassaPayments',
    :git => 'https://github.com/yoomoney/yookassa-payments-swift.git',
    :tag => '6.1.0'
`
Не собирается и в версии 6.1.0

**Comment by starxor** [comment]
@kirsantov должно быть исправлено в 6.1.1. Пожалуйста. Дайте знать если проблема всё ещё присутствует.
