### ISSUE TITLE
Ошибка 'PaymentMethodType' is ambiguous for type lookup in this context 'Tokens' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by bits84** [yoomoney/yookassa-payments-swift#103]
Использую xcod 12.4 перешил на версию 5.3.0, лучил обновленный `TMXProfiling` и `TMXProfilingConnections`.
закинул используя Finder в корень проекта TMXProfiling.xcframework и TMXProfilingConnections.xcframework.

В разделе General у основного таргета проекта добавил TMXProfiling.xcframework и TMXProfilingConnections.xcframework в Frameworks, Libraries, and Embedded Content

при сборке проекта ругается
![PaymentsViewController_swift](https://user-images.githubusercontent.com/1576163/115126160-c82a5500-9fd5-11eb-82e7-d1a54f69b1d5.png)

что делаю не так?

**Comment by pavlof01** [comment]
попробуй удалить import YooKassaPaymentsApi

**Comment by bits84** [comment]
Спасибо. помогло

**Comment by Cigan12** [comment]
+1 помогло)
