### ISSUE TITLE
ThreatMetrixAdapter.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion.

### ISSUE THREAD

**Issue by pavlof01** [yoomoney/yookassa-payments-swift#104]
Frameworks/ThreatMetrixAdapter.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion.

Верси 5.3.0, добавил все новые файлы, в режиме дебаг нормально работает.

Ошибку выдает при выгрузке в test flight, я вручную добавил версию, но это нельзя назвать решением, приходится каждый раз добавлять после архивации

**Comment by oltv00** [comment]
@pavlof01 

Решили не выпускать новую версию, а подменить текущую `ThreatMetrixAdapter` 2.0.0 с добавлением CFBundleVersion в Info.plist

Чтобы обновить `ThreatMetrixAdapter` локально, думаю будет достаточно выполнить:

```
pod update ThreatMetrixAdapter
```

Если проблема сохранится, можно почистить pod-repo и потом установить зависимости:

```
rm -rf ~/.cocoapods/repos/yoomoney-tech/
pod install
```

**Comment by abdulgamidov** [comment]
> @pavlof01
> 
> Решили не выпускать новую версию, а подменить текущую `ThreatMetrixAdapter` 2.0.0 с добавлением CFBundleVersion в Info.plist
> 
> Чтобы обновить `ThreatMetrixAdapter` локально, думаю будет достаточно выполнить:
> 
> ```
> pod update ThreatMetrixAdapter
> ```
> 
> Если проблема сохранится, можно почистить pod-repo и потом установить зависимости:
> 
> ```
> rm -rf ~/.cocoapods/repos/yoomoney-tech/
> pod install
> ```

Данное решение не помогло =(

**Comment by oltv00** [comment]
@abdulgamidov 
Такая же ошибка ?
И ошибка на CI или локально ?
100% уверен в том что это кэш.

Если локально, то можно еще попробовать удалить папку Pods/

т.е. 

```
rm -rf ~/.cocoapods/repos/yoomoney-tech/
rm -rf Pods/
pod install
```

Еще возможно в первом пункте вместо `pod update ThreatMetrixAdapter` выполнить `pod update YooKassaPayments`

**Comment by abdulgamidov** [comment]
Продела все выше указанное, но все равно при выгрузке билда выдает такую же ошибку - The Info.plist file is missing the required key: CFBundleVersion.
Такой вопрос, нужно ли все таки вручную добавлять версию ?

**Comment by pavlof01** [comment]
@oltv00 не помогает

**Comment by bits84** [comment]
кто нашел решение?

**Comment by pavlof01** [comment]
@bits84 пока-что вручную или скриптом проставлять версию, ждем официального решения

**Comment by bits84** [comment]
@pavlof01  подскажи где проставлять надо?  /ThreatMetrixAdapter/ThreatMetrixAdapter.xcframework/Info.plist тут?

**Comment by pavlof01** [comment]
@bits84 нет, когда сбилдил апку, заходишь в его через show package content, ищешь папку ThreatMetrixConnection и там в info.plist проставляешь версию любую.
Либо:
`find . -name 'Info.plist' -not -path "*.storyboard*"  | while read file; do echo $file; { plutil -p $file | grep CFBundleVersion; } || echo Failed $file; done;`

**Comment by pavlof01** [comment]
@oltv00 any updates???

**Comment by oltv00** [comment]
> @bits84 нет, когда сбилдил апку, заходишь в его через show package content, ищешь папку ThreatMetrixConnection и там в info.plist проставляешь версию любую.
> Либо:
> [https://developer.apple.com/forums/thread/23778](url)
> `find . -name 'Info.plist' -not -path "*.storyboard*" | while read file; do echo $file; { plutil -p $file | grep CFBundleVersion; } || echo Failed $file; done;`

Подождите, а при чем тут `ThreatMetrixConnection` ?
Проблема была в зависимости `ThreatMetrixAdapter`, в info.plist не было ключа `CFBundleVersion`.
В текущей версии `ThreatMetrixAdapter` 2.0.0 этот ключ есть.

У кого воспроизводится проблема локально, предлагаю следующий алгоритм решения:
В папке с проектом выполнить в консоли:
```zsh
rm -rf ~/.cocoapods/repos/yoomoney-tech/
rm -rf ~/Library/Caches/CocoaPods/
rm -rf Pods/
pod install
```

Дальше попробовать собрать Archive и сделать Validate.

**Comment by pavlof01** [comment]
@oltv00 спасибо, помогло
