### ISSUE TITLE
Совместимость с новой версией AppMetrica

### ISSUE THREAD

**Issue by underqcool** [yoomoney/yookassa-payments-swift#107]
Привет,

Нашему приложению необходимо поддерживать AppMetrica 3.15.1+ (из-за нового способа работы с IDFA), ваш SDK сейчас использует 3.12.0, из-за чего у нас некорректно работает аналитика.

CocoaPods принудительно повысить версию не позволяет из-за ограничения версии в вашем Podfile. Можете подсказать способ обойти это или обновить библиотеку?

**Comment by oltv00** [comment]
@underqcool 

Привет!

Сегодня обновим версию AppMetrica в podspec

**Comment by oltv00** [comment]
@underqcool 

https://github.com/yoomoney/yookassa-payments-swift/releases/tag/5.4.1
