### ISSUE TITLE
SDK не собирается для симулятора(архитектура: arm64-apple-ios-simulator) на m1 процессорах.

### ISSUE THREAD

**Issue by cmuphobk** [yoomoney/yookassa-payments-swift#108]
Внутри SDK есть ThreatMetrixAdapter.xcframework, который не собран для arm64-apple-ios-simulator архитектуры.
Также необходимо будет убедиться что TMXProfiling и TMXProfilingConnections передаваемые менеджерами включают arm64-apple-ios-simulator (https://github.com/yoomoney/yookassa-payments-swift#подключение-tmxprofiling-и-tmxprofilingconnections).

```Could not find module 'ThreatMetrixAdapter' for target 'arm64-apple-ios-simulator'; found: i386, x86_64-apple-ios-simulator, x86_64, i386-apple-ios-simulator```

<img width="411" alt="Снимок экрана 2021-06-07 в 13 32 05" src="https://user-images.githubusercontent.com/12449923/120993841-fbe35900-c794-11eb-9548-ffaab8893dc9.png">

**Comment by cmuphobk** [comment]
@oltv00 У вас ведутся какие-то работы в эту сторону? Есть смысл ждать апдейта?

**Comment by LavTeamProject** [comment]
Присоединяюсь к вопросу.
Очень сильно мешает, на данный момент только из-за yookassa приходится держать intel mac

**Comment by starxor** [comment]
Обновлённая версия библиотек с поддержкой симуляторов на мак с процессорами M1 доступна у наших менеджеров. Пожалуйста обращайтесь к менеджерам для получения обновления.
