### ISSUE TITLE
Некорректное отображение шторки выбора оплаты

### ISSUE THREAD

**Issue by IgorFedorchuk** [yoomoney/yookassa-payments-swift#110]
На X телефонах нижняя полоска телефона наезжает на выбор оплаты. Версия сдк 6.0.0, iOS 14.6
http://joxi.ru/LmG4XlvtgJ3gX2

**Comment by oltv00** [comment]
При интеграции в пустой проект - баг не воспроизводится.
Выясняем причину почему так происходит.

**Comment by starxor** [comment]
исправлено в 6.1.1
