### ISSUE TITLE
ThreatMetrixServiceFactory fatal error

### ISSUE THREAD

**Issue by wwwhttpru** [yoomoney/yookassa-payments-swift#115]
Thread 1: Fatal error: The operation couldn’t be completed. (ThreatMetrixAdapter.ThreatMetrixAdapterError error 1.)
![image](https://user-images.githubusercontent.com/56841516/128988742-a04c37fc-31b1-4438-b1e5-541e02fdc276.png)

**Comment by wwwhttpru** [comment]
This error only occurs on the emulator.
Everything is fine on a real device

**Comment by starxor** [comment]
Пожалуйста запросите и наших менеджеров библиотеки TMX(ThreatMetrix) и подключите в ваш проект. ([как подключить](https://github.com/yoomoney/yookassa-payments-swift/blob/master/README_RU.md#подключение-tmxprofiling-и-tmxprofilingconnections))
Please ask our managers for TMX(ThreatMetrix) libraries & link them with your project. ([hot to link](https://github.com/yoomoney/yookassa-payments-swift#implementing-tmxprofiling-and-tmxprofilingconnections))
