### ISSUE TITLE
Краш YooKassaPayments/ThreatMetrixServiceFactory.swift:11: Fatal error: Не удалось завершить операцию.

### ISSUE THREAD

**Issue by akonoplev** [yoomoney/yookassa-payments-swift#117]
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/26434897/135341537-03e78e5b-53d0-4d0a-81bb-220606c8c2b7.png">

Либа падает на реальном устройстве

**Comment by balkarov** [comment]
Добрый день. Удалось исправить проблему?

**Comment by lxndrvla** [comment]
Здравствуйте, та же самая проблема

**Comment by starxor** [comment]
Запросите у менеджера TMX фреймворки и добавьте в проект [как описано здесь](https://github.com/yoomoney/yookassa-payments-swift/blob/master/README_RU.md#подключение-tmxprofiling-и-tmxprofilingconnections)
