### ISSUE TITLE
ThreatMetrixAdapter.ThreatMetrixAdapterError

### ISSUE THREAD

**Issue by lxndrvla** [yoomoney/yookassa-payments-swift#120]
Добрый вечер 
Возникает данная ошибка на реальном устройстве 

![Снимок экрана 2021-11-15 в 20 46 22](https://user-images.githubusercontent.com/92423886/141801727-53861f85-71db-43f4-a7ac-54261dcdfb38.png)

Может ли быть проблема в том, что менеджер ЮКассы скинул мне только TrustDefender.framework

**Comment by starxor** [comment]
да. запросите у менеджера TMX библиотеки и добавьте в проект согласно [TMXProfiling](https://github.com/yoomoney/yookassa-payments-swift/blob/master/README_RU.md#подключение-tmxprofiling-и-tmxprofilingconnections)
