### ISSUE TITLE
Присоединяют

### ISSUE THREAD

**Issue by bits84** [yoomoney/yookassa-payments-swift#121]
Присоединяют

> Ориентировочно в декабре 2021 появится поддержка arm64-apple-ios-simulator в самих библиотеках ThreatMetrix. В последние версии ThreatMetrixAdapter вкулючена поддержка данной архитектуры, но пока она не появится в TMXProfiling/TMXProfilingConnections на arm64 симуляторе, к сожалению, собирать проект возможности не будет.

Спасибо за ответ! Присоединяюсь к вопросу, очень актуально 👍

_Originally posted by @eyurchuk in https://github.com/yoomoney/yookassa-payments-swift/issues/108#issuecomment-950049784_

**Comment by starxor** [comment]
Обновлённая версия библиотек с поддержкой симуляторов на мак с процессорами M1 доступна у наших менеджеров. Пожалуйста обращайтесь к менеджерам для получения обновления.
