### ISSUE TITLE
Крашится приложение при вызове платежного модуля на iOS 15.1

### ISSUE THREAD

**Issue by ialeshqa** [yoomoney/yookassa-payments-swift#123]
На iOS 15.0.1 все работает корректно, на обновленной прошивке вылетает приложение при вызове платежного модуля 

Метод:

`
    DispatchQueue.main.async {
      (UIApplication.shared.delegate as? AppDelegate)?.window?.rootViewController?.present(self.viewController as! UIViewController, animated: true, completion: nil)
    }`

crashlog во вложени
[crashlog.crash.zip](https://github.com/yoomoney/yookassa-payments-swift/files/7605167/crashlog.crash.zip)

**Comment by VladlenKaveev** [comment]
+1

**Comment by VladlenKaveev** [comment]
@ialeshqa нашел какой-нибудь способ для решения проблемы?

**Comment by ialeshqa** [comment]
> @ialeshqa нашел какой-нибудь способ для решения проблемы?

поддержка посоветовала обновить библиотеку, не проверяли еще этот спос
[ThreatMetrix6.2.zip](https://github.com/yoomoney/yookassa-payments-swift/files/7608256/ThreatMetrix6.2.zip)
об

**Comment by alex-snap** [comment]
> +1

+1

**Comment by VladlenKaveev** [comment]
@ialeshqa а какая у вас версия SDK кассы установлена? Просто мы используем 6.0.0 и вот думаю поможет ли обновление до новой версии)

**Comment by Liptor** [comment]
@VladlenKaveev удалось решить проблему? у нас обновление библиотеки до версии 6.4.0 не сработало

**Comment by VladlenKaveev** [comment]
@Liptor пока нет 😕

**Comment by VladlenKaveev** [comment]
@ialeshqa @ialeshqa 
Посмотрев аналогичные проблемы у других, все-таки удалось заставить модуль работать на iOS 15.1)

Было:
`
...

let inputData: TokenizationFlow = .tokenization(tokenizationModuleInputData)
viewController = TokenizationAssembly.makeModule(inputData: inputData, moduleOutput: self)
DispatchQueue.main.async {
            let rootViewController = UIApplication.shared.keyWindow!.rootViewController!
            rootViewController.present(self.viewController!, animated: true, completion: nil)
        }
`

Стало: 
`
DispatchQueue.main.async {
            let inputData: TokenizationFlow = .tokenization(tokenizationModuleInputData)
            self.viewController = TokenizationAssembly.makeModule(inputData: inputData, moduleOutput: self)
            let rootViewController = UIApplication.shared.keyWindow!.rootViewController!
            rootViewController.present(self.viewController!, animated: true, completion: nil)
        }
`

P.S 
Еще не тестировали на других версиях iOS

**Comment by starxor** [comment]
Закрываю вопрос. Так как он не связан с библиотекой напрямую. Ошибка происходила из-за презентации UI со второстепенного потока.
