### ISSUE TITLE
Ошибки FunctionalSwift и MoneyAuth

### ISSUE THREAD

**Issue by kuznetsov-from-wonderland** [yoomoney/yookassa-payments-swift#127]
```
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/yoomoney-tech/cocoa-pod-specs.git'
plugin 'cocoapods-user-defined-build-types'
enable_user_defined_build_types!

platform :ios, '13.0'

  pod 'YooKassaPayments',
    :build_type => :dynamic_framework,
    :git => 'https://github.com/yoomoney/yookassa-payments-swift.git',
    :tag => '5.4.1'


swift --version
swift-driver version: 1.26.9 Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)
Target: arm64-apple-macosx12.0

XCode 13.1

```

Случается ошибка

```

Showing Recent Errors Only
......./ios/Pods/YooKassaPayments/YooKassaPayments/Private/Services/Authorization/AuthorizationServiceAssembly.swift:1:8: Failed to build module 'MoneyAuth'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)', while this compiler is 'Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)'). Please select a toolchain which matches the SDK.
```

![CleanShot 2022-02-11 at 14 33 25](https://user-images.githubusercontent.com/33729094/153584575-7dbc722b-27b8-4f2a-9cab-09ce2d93ea13.png)

**Comment by kuznetsov-from-wonderland** [comment]
@starxor
Посмотри, пожалуйста?

**Comment by kuznetsov-from-wonderland** [comment]
Хотелось бы остаться на 5й версии, прямо сейчас нет возможности обновиться

**Comment by kuznetsov-from-wonderland** [comment]
Возможно относится к той же проблеме? После `pod install` случаются warnings
![CleanShot 2022-02-11 at 14 47 28](https://user-images.githubusercontent.com/33729094/153586360-1f6e92d8-7de1-4819-a1fe-b6995305eadb.png)

**Comment by kuznetsov-from-wonderland** [comment]
Еще больше деталей(
![CleanShot 2022-02-11 at 15 03 48](https://user-images.githubusercontent.com/33729094/153588379-5abbf6d8-14cd-41a4-a527-cec21e7e56d3.png)
В Podfile.lock установилась версия `- FunctionalSwift (1.2.0)`

Может стоит припинить другую версию?

**Comment by starxor** [comment]
Вероятно ошибку для FunctionalSwift получится убрать изменением версии. Похоже что более серьёзная проблема это вот эта ошибка
`Failed to build module 'MoneyAuth'; this SDK is not supported by the compiler (the SDK is built with 'Ap..`
