### ISSUE TITLE
Duplicate Assets.car - конфликт с новой билд системой (New Build System)

### ISSUE THREAD

**Issue by iwheelbuy** [yoomoney/yookassa-payments-swift#53]
Существует проблема конфликта ассетов разных фреймворков в проекте собираемым новой билд системой Xcode. Подробнее можно почитать [issue на сам CocoaPods](https://github.com/CocoaPods/CocoaPods/issues/8122). То, с чем я столкнулся интегрируя ваш фреймворк, полностью совпадает с проблемой описанной в issue. Быстрым решением является отказ от новой билд системы, более сложные решения опять же можно почитать в [issue на сам CocoaPods](https://github.com/CocoaPods/CocoaPods/issues/8122).

**Comment by oltv00** [comment]
@iwheelbuy 
Привет!
Подскажи, почему закрыли issue?
Может ли проблема быть решена на нашей стороне?

**Comment by iwheelbuy** [comment]
Просто задачей интеграции Яндекс кассы я пока не буду заниматься, вот и закрыл issue.
Не знаю, я не успел подумать над этим. Если вдруг вернусь к задаче, то обязательно попробую подумать над решением.

**Comment by oltv00** [comment]
@iwheelbuy 
Я открою issue чтобы не потерять, в течении след. 2-ух недель планирую разобраться.

По результатам отпишу сюда.

**Comment by starxor** [comment]
более не актуально
