### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by nenecmrf** [yoomoney/yookassa-payments-swift#58]
Возникает ошибка при попытке сборки

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_THMTrustDefender", referenced from:
      objc-class-ref in libYandexCheckoutPayments.a(ThreatMetrixService.o)
  "_THMProfileStatus", referenced from:
      function signature specialization <Arg[1] = Dead> of static YandexCheckoutPayments.ThreatMetrixService.(handleProfilingResult in _494410973FF5E845E89AB1306ACCEB6D)([Swift.AnyHashable : Any]?) -> () in libYandexCheckoutPayments.a(ThreatMetrixService.o)
  "_THMSessionID", referenced from:
      function signature specialization <Arg[1] = Dead> of static YandexCheckoutPayments.ThreatMetrixService.(handleProfilingResult in _494410973FF5E845E89AB1306ACCEB6D)([Swift.AnyHashable : Any]?) -> () in libYandexCheckoutPayments.a(ThreatMetrixService.o)
  "_THMOrgID", referenced from:
      function signature specialization <Arg[0] = Dead> of closure #1 () -> () in static YandexCheckoutPayments.ThreatMetrixService.configure() -> () in libYandexCheckoutPayments.a(ThreatMetrixService.o)
  "_THMFingerprintServer", referenced from:
      function signature specialization <Arg[0] = Dead> of closure #1 () -> () in static YandexCheckoutPayments.ThreatMetrixService.configure() -> () in libYandexCheckoutPayments.a(ThreatMetrixService.o)
  "_THMTimeout", referenced from:
      function signature specialization <Arg[0] = Dead> of closure #1 () -> () in static YandexCheckoutPayments.ThreatMetrixService.configure() -> () in libYandexCheckoutPayments.a(ThreatMetrixService.o)
  "_THMLocationServices", referenced from:
      function signature specialization <Arg[0] = Dead> of closure #1 () -> () in static YandexCheckoutPayments.ThreatMetrixService.configure() -> () in libYandexCheckoutPayments.a(ThreatMetrixService.o)
  "_THMUseNSURLSession", referenced from:
      function signature specialization <Arg[0] = Dead> of closure #1 () -> () in static YandexCheckoutPayments.ThreatMetrixService.configure() -> () in libYandexCheckoutPayments.a(ThreatMetrixService.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by bobile** [comment]
попробуй позапускать с разными билд-конфигурациями Release/Debug. мне помогло, когда я выбрал Debug вместо кастомной конфигурации, которую дублировал от Debug.

**Comment by oltv00** [comment]
@nenecmrf 
привет!

получилось решить проблему ?

**Comment by oltv00** [comment]
@nenecmrf 
Закрою issue, т.к. нет активности, если проблема возникнет опять, можно переоткрыть, или создать новую.
