### ISSUE TITLE
Русификация интерфейса.

### ISSUE THREAD

**Issue by bondsy777** [yoomoney/yookassa-payments-swift#59]
Подключил яндекс кассу (3.3.0) к проекту на objective-c, но есть одна проблема, не удается русифицировать интерфейс. Русификация приложения не помогла. На устройстве смена языков ни как не влияет на локализацию в интерфейсе яндекс кассы. Есть решение, подскажите, пожалуйста?

**Comment by oltv00** [comment]
@bondsy777 
привет!
получилось решить проблему ?

для ее решения необходимо чтобы в настройках проекта была английская и русская локализация.
![image](https://user-images.githubusercontent.com/14943414/103078706-7f443000-45e3-11eb-946d-b3d88f41a1ef.png)

**Comment by astarusdev** [comment]
> @bondsy777
> привет!
> получилось решить проблему ?
> 
> для ее решения необходимо чтобы в настройках проекта была английская и русская локализация.
> ![image](https://user-images.githubusercontent.com/14943414/103078706-7f443000-45e3-11eb-946d-b3d88f41a1ef.png)

<img width="695" alt="Screenshot 2020-12-24 at 14 42 31" src="https://user-images.githubusercontent.com/55095893/103083658-59745680-45f6-11eb-9ea3-0a48313663bd.png">

не работает.

**Comment by oltv00** [comment]
@astarusdev 
А есть возможность прислать мне тестовый проект в котором это воспроизводится ?
Прислать лучше на почту oltv00@gmail.com или Telegram `@oltv00`

Я воспроизвести, к сожалению не смог. (пробовал переключать development language)
![image](https://user-images.githubusercontent.com/14943414/103089488-1c609200-45ff-11eb-884a-9138255cacc7.png)

**Comment by oltv00** [comment]
@astarusdev 
хочу вернуться к проблеме.
воспроизвести я ее к сожалению не могу, нужно больше информации.
на почте и в Telegram проекта я не видел.
есть возможность прислать тестовый проект в котором воспроизводится данный кейс ?
