### ISSUE TITLE
No such module TMXProfiling in YandexCheckoutPayments

### ISSUE THREAD

**Issue by MadGeorge** [yoomoney/yookassa-payments-swift#62]
В абсолютно новый Single View iOS проект добавлена зависимость на это pod v 3.5.0, pod init.
В проект закинуты TMXProfiling и TMXProfilingConnections. Добавлен Run Script, присланный с этими фреймворками.
Все как описано в "Подключение зависимостей" и "Подключение TMXProfiling и TMXProfilingConnections".

Но! Хоть ты тресни, ```No such module TMXProfiling``` в модуле YandexCheckoutPayments.   

![Screenshot 2020-05-15 at 15 10 43](https://user-images.githubusercontent.com/25031713/82050971-adfb3f00-96c1-11ea-8503-eb21240627dd.png)

<img src="https://user-images.githubusercontent.com/25031713/82050769-64125900-96c1-11ea-8d08-b59732623754.png" data-canonical-src="https://user-images.githubusercontent.com/25031713/82050769-64125900-96c1-11ea-8d08-b59732623754.png" width="200" /><img src="https://user-images.githubusercontent.com/25031713/82051167-0df1e580-96c2-11ea-917e-7c5f9294f8a1.png" data-canonical-src="https://user-images.githubusercontent.com/25031713/82051167-0df1e580-96c2-11ea-917e-7c5f9294f8a1.png" width="450" />

Я, конечно понимаю, что я один такой одаренный и у всех остальных все нормально собирается, но можно еще раз для тупых пояснить - каким боком модуль YandexCheckoutPayments должен получить доступ к зависимостям основного проекта? 
На скриншотах видно, что frameworks search path из этого пода смотрит типа туда куда вы хотели ($(PODS_ROOT)/../Frameworks), но это не особо помогает. 

Из любопытства я закинул TMXProfiling в проект Pods с таргетом на фреймворк-аггрегатор, и проект стал собираться. Но в рантайме он конечно же падает с ошибкой ```dylib image not found```, что не удивительно. 

Перезагружать икскоды и чистить derived data не предлагать. 

cocoapods v 1.9.1
macOS 10.15.4 (19E287) Xcode 11.4.1 (11E503a)
YandexCheckoutPayments 3.5.0

**Comment by MadGeorge** [comment]
Есть кто живой?

**Comment by oltv00** [comment]
@MadGeorge 
Привет!
Это у тебя тестовый проект?
Можешь его .zip в ссылке мне прислать?
Ссылку можно на почту oltv00@gmail.com или в Telegram `@oltv00`

**Comment by MadGeorge** [comment]
@oltv00 здравствуйте. Спасибо за ответ. Отправил архив на oltv00@gmail.com

**Comment by oltv00** [comment]
@MadGeorge 
Посмотрел тестовый проект.
Неверно был выполнен пункт
![Screenshot 2020-05-19 at 11 03 28](https://user-images.githubusercontent.com/14943414/82301083-6aa21880-99c0-11ea-8df4-f3ad5fd88753.png)

Нужно физически создать папку Frameworks через Finder и поместить туда фреймворки.
На почту отправил проект с фиксом.

**Comment by MadGeorge** [comment]
Проект собирается, спасибо.
Пункт совершенно не очевидный. В Xcode не видно разницы между группой и физической директорией на диске. К тому же формулировка "если в проекте отсутсвует папка" не говорит ничего о "физически". Смотрю в Xcode - виду Frameworks, по русски это "папка".
За ответ и помощь спасибо.

**Comment by MadGeorge** [comment]
Кстати, если скачать этот репозиторий и пробовать запустить пример, история будет ровно такая же - физической директории Frameworks нет.

**Comment by oltv00** [comment]
@MadGeorge 
Да, спасибо, этот момент получше опишем и поправим в репозитории.
Дело в том что в репозитории нельзя хранить эти фреймворки, а пустую папку видимо git не воспринимает.

**Comment by hellc** [comment]
@oltv00 а есть объективная причина почему эти фреимворки (TMX*.framework) нельзя подтягивать автоматически из внешних источников; и почему самих источников тоже нет?

**Comment by oltv00** [comment]
@hellc есть.
причина - юридическая.
framework нельзя выкладывать в открытый доступ.
