### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by null-z** [yoomoney/yookassa-payments-swift#63]
Обновил с 2.3.1 до 3.5.0. TrustDefender был заменен TMXProfiling и TMXProfilingConnections with bitcode и остальные шаги в соответствии с инструкцией.
 Проект собирается/запускается, всё работает. 
Архивируется, успешно проходит валидацию, отправляется App Store Connect, но уже в App Store Connect на этапе обработки фэйлится.  

Вот такой отчет приходит на почту: 
While processing your iOS app, MyApp, errors occurred in the app thinning process, and your app couldn’t be thinned. If your app contains bitcode, bitcode processing may have failed. Because of these errors, this build of your app will not be able to be submitted for review or placed on the App Store. For information that may help resolve this issue, see Tech Note 2432.  

При попытке дистрибьюции методом Development тоже фэйлится.  Вот часть отчета: 

-= Output =-
    ld: warning: -sdk_version and -platform_version are not compatible, ignoring -sdk_version
    Undefined symbols for architecture arm64:
      "__yandex_impl__vkDestroyDescriptorSetLayout", referenced from:
          __hidden#135293_ in 1956.o
      "__yandex_impl__vkCreateDescriptorSetLayout", referenced from:
          __hidden#136070_ in 1956.o
      "__yandex_impl__vkCreateSwapchainKHR", referenced from:
          __hidden#136059_ in 1954.o
      "__yandex_impl__vkGetDeviceQueue", referenced from:
          __hidden#136047_ in 1953.o
      "__yandex_impl__vkEnumeratePhysicalDevices", referenced from:
          __hidden#136009_ in 1949.o
      "__yandex_impl__vkGetPhysicalDeviceFormatProperties", referenced from:
          __hidden#136009_ in 1949.o
      "__yandex_impl__vkWaitForFences", referenced from:
          __hidden#135741_ in 1948.o
          __hidden#136008_ in 1948.o
      "__yandex_impl__vkResetFences", referenced from:
          __hidden#135742_ in 1948.o
      "__yandex_impl__vkCreateFence", referenced from:
          __hidden#136006_ in 1948.o
      "__yandex_impl__vkCreateIOSSurfaceMVK", referenced from:
          __hidden#135995_ in 1946.o
      "__yandex_impl__vkGetPhysicalDeviceSurfacePresentModesKHR", referenced from:
          __hidden#135995_ in 1946.o
      "__yandex_impl__vkDestroySurfaceKHR", referenced from:
          __hidden#135995_ in 1946.o
          __hidden#135998_ in 1946.o
      "__yandex_impl__vkUpdateDescriptorSets", referenced from:
          __hidden#135198_ in 1943.o
      "__yandex_impl__vkCreatePipelineLayout", referenced from:
          __hidden#135956_ in 1940.o
      "__yandex_impl__vkDestroyInstance", referenced from:
          __hidden#135907_ in 1936.o
      "__yandex_impl__vkEnumerateInstanceLayerProperties", referenced from:
          __hidden#135904_ in 1936.o
      "__yandex_impl__vkDestroySwapchainKHR", referenced from:
          __hidden#135717_ in 1954.o
      "__yandex_impl__vkDestroySampler", referenced from:
          __hidden#135248_ in 1933.o
      "__yandex_impl__vkCreateSemaphore", referenced from:
          __hidden#135728_ in 1930.o
      "__yandex_impl__vkDestroyImage", referenced from:
          __hidden#135385_ in 1929.o
          __hidden#135719_ in 1929.o
          __hidden#135720_ in 1929.o
      "__yandex_impl__vkGetPhysicalDeviceSurfaceFormatsKHR", referenced from:
          __hidden#135995_ in 1946.o
      "__yandex_impl__vkEnumerateInstanceExtensionProperties", referenced from:
          __hidden#135904_ in 1936.o
      "__yandex_impl__vkAcquireNextImageKHR", referenced from:
          __hidden#135566_ in 1928.o
      "__yandex_impl__vkCreateSampler", referenced from:
          __hidden#135893_ in 1933.o
      "__yandex_impl__vkCreateShaderModule", referenced from:
          __hidden#135688_ in 1925.o
      "__yandex_impl__vkDestroyFramebuffer", referenced from:
          __hidden#135687_ in 1924.o
      "__yandex_impl__vkGetPhysicalDeviceSurfaceCapabilitiesKHR", referenced from:
          __hidden#135995_ in 1946.o
          __hidden#135700_ in 1946.o
      "__yandex_impl__vkCreateFramebuffer", referenced from:
          __hidden#135684_ in 1924.o
      "__yandex_impl__vkGetPhysicalDeviceProperties", referenced from:
          __hidden#136009_ in 1949.o
      "__yandex_impl__vkQueueSubmit", referenced from:
          __hidden#135952_ in 1938.o
      "__yandex_impl__vkDestroySemaphore", referenced from:
          __hidden#135731_ in 1930.o
      "__yandex_impl__vkQueuePresentKHR", referenced from:
          __hidden#135572_ in 1923.o
      "__yandex_impl__vkFreeMemory", referenced from:
          __hidden#135518_ in 1916.o
          __hidden#135519_ in 1916.o
      "__yandex_impl__vkDestroyRenderPass", referenced from:
          __hidden#135584_ in 1921.o
      "__yandex_impl__vkCreateInstance", referenced from:
          __hidden#135903_ in 1936.o
      "__yandex_impl__vkDestroyShaderModule", referenced from:
          __hidden#135691_ in 1925.o
      "__yandex_impl__vkCreateRenderPass", referenced from:
          __hidden#135651_ in 1921.o
      "__yandex_impl__vkCreateGraphicsPipelines", referenced from:
          __hidden#135645_ in 1920.o
      "__yandex_impl__vkAllocateDescriptorSets", referenced from:
          __hidden#135195_ in 1919.o
      "__yandex_impl__vkDeviceWaitIdle", referenced from:
          __hidden#135549_ in 1917.o
          __hidden#135554_ in 1917.o
          __hidden#135562_ in 1917.o
      "__yandex_impl__vkUnmapMemory", referenced from:
          __hidden#135521_ in 1916.o
      "__yandex_impl__vkCreateImageView", referenced from:
          __hidden#135391_ in 1947.o
      "__yandex_impl__vkDestroyPipeline", referenced from:
          __hidden#135648_ in 1920.o
      "__yandex_impl__vkMapMemory", referenced from:
          __hidden#135520_ in 1916.o
      "__yandex_impl__vkAllocateMemory", referenced from:
          __hidden#135513_ in 1916.o
      "__yandex_impl__vkCreateBuffer", referenced from:
          __hidden#135512_ in 1916.o
      "__yandex_impl__vkDestroyDevice", referenced from:
          __hidden#135225_ in 1902.o
          __hidden#135229_ in 1902.o
      "__yandex_impl__vkEndCommandBuffer", referenced from:
          __hidden#135215_ in 1910.o
      "__yandex_impl__vkGetBufferMemoryRequirements", referenced from:
          __hidden#135512_ in 1916.o
      "__yandex_impl__vkBindBufferMemory", referenced from:
          __hidden#135512_ in 1916.o
      "__yandex_impl__vkResetDescriptorPool", referenced from:
          __hidden#135640_ in 1919.o
      "__yandex_impl__vkCmdBeginRenderPass", referenced from:
          __hidden#135189_ in 1910.o
      "__yandex_impl__vkDestroyCommandPool", referenced from:
          __hidden#135338_ in 1911.o
      "__yandex_impl__vkGetPhysicalDeviceMemoryProperties", referenced from:
          __hidden#135511_ in 1916.o
      "__yandex_impl__vkAllocateCommandBuffers", referenced from:
          __hidden#135340_ in 1911.o
      "__yandex_impl__vkCmdBindVertexBuffers", referenced from:
          __hidden#135210_ in 1910.o
          __hidden#135212_ in 1910.o
      "__yandex_impl__vkFreeCommandBuffers", referenced from:
          __hidden#135363_ in 1911.o
      "__yandex_impl__vkDestroyFence", referenced from:
          __hidden#135744_ in 1948.o
      "__yandex_impl__vkCreateCommandPool", referenced from:
          __hidden#135335_ in 1911.o
      "__yandex_impl__vkCmdBindIndexBuffer", referenced from:
          __hidden#135212_ in 1910.o
      "__yandex_impl__vkCmdBindDescriptorSets", referenced from:
          __hidden#135199_ in 1910.o
      "__yandex_impl__vkGetSwapchainImagesKHR", referenced from:
          __hidden#135709_ in 1954.o
      "__yandex_impl__vkCmdDraw", referenced from:
          __hidden#135208_ in 1910.o
          __hidden#135210_ in 1910.o
      "__yandex_impl__vkGetPhysicalDeviceSurfaceSupportKHR", referenced from:
          __hidden#135254_ in 1906.o
          __hidden#135255_ in 1906.o
      "__yandex_impl__vkBeginCommandBuffer", referenced from:
          __hidden#135329_ in 1910.o
      "__yandex_impl__vkDestroyPipelineLayout", referenced from:
          __hidden#135649_ in 1940.o
      "__yandex_impl__vkGetInstanceProcAddr", referenced from:
          __hidden#135903_ in 1936.o
          __hidden#135905_ in 1936.o
      "__yandex_impl__vkCmdPushConstants", referenced from:
          __hidden#135205_ in 1910.o
      "__yandex_impl__vkCmdDrawIndexed", referenced from:
          __hidden#135212_ in 1910.o
      "__yandex_impl__vkCreateDescriptorPool", referenced from:
          __hidden#135639_ in 1919.o
      "__yandex_impl__vkCmdBindPipeline", referenced from:
          __hidden#135192_ in 1910.o
      "__yandex_impl__vkDestroyDescriptorPool", referenced from:
          __hidden#135635_ in 1919.o
      "__yandex_impl__vkCmdSetViewport", referenced from:
          __hidden#135192_ in 1910.o
      "__yandex_impl__vkCmdCopyBuffer", referenced from:
          __hidden#135331_ in 1910.o
      "__yandex_impl__vkDestroyImageView", referenced from:
          __hidden#135398_ in 1947.o
          __hidden#136002_ in 1947.o
          __hidden#136003_ in 1947.o
      "__yandex_impl__vkCmdSetScissor", referenced from:
          __hidden#135192_ in 1910.o
      "__yandex_impl__vkGetImageMemoryRequirements", referenced from:
          __hidden#135514_ in 1916.o
      "__yandex_impl__vkCmdEndRenderPass", referenced from:
          __hidden#135214_ in 1910.o
      "__yandex_impl__vkCmdCopyBufferToImage", referenced from:
          __hidden#135332_ in 1910.o
      "__yandex_impl__vkCreateImage", referenced from:
          __hidden#135514_ in 1916.o
      "__yandex_impl__vkCmdPipelineBarrier", referenced from:
          __hidden#135330_ in 1910.o
      "__yandex_impl__vkGetPhysicalDeviceQueueFamilyProperties", referenced from:
          __hidden#135255_ in 1906.o
      "__yandex_impl__vkDestroyBuffer", referenced from:
          __hidden#135251_ in 1905.o
      "__yandex_impl__vkCreateDevice", referenced from:
          __hidden#135225_ in 1902.o
      "__yandex_impl__vkBindImageMemory", referenced from:
          __hidden#135514_ in 1916.o
    ld: symbol(s) not found for architecture arm64
    Exited with 1
    
    Failed to compile bundle: /var/folders/05/vs11370j15q46m1fz9xjy9m40000gn/T/MyApp3bfa0j_b/MyApp.arm64.xar

Stderr:

>
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:297:in `run'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2706:in `block in CompileOrStripBitcodeInBundle'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2645:in `each'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2645:in `CompileOrStripBitcodeInBundle'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2905:in `block in ProcessIPA'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2867:in `each'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2867:in `ProcessIPA'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:3814:in `<main>'

**Comment by oltv00** [comment]
@null-z 
привет!
получилось ли решить проблему?

**Comment by null-z** [comment]
Привет!
Более попыток обновления не было, а я больше над тем проектом не работаю.
