### ISSUE TITLE
Ошибка  - No such module 'TMXProfiling'

### ISSUE THREAD

**Issue by Sunrizzin** [yoomoney/yookassa-payments-swift#64]
Добрый день! 

Устанавливаю библиотеку через Cocoapods. Установилась версия 3.5.0
 При сборке получаю ошибку **No such module 'TMXProfiling'**. 
Но таких библиотек в проекте нет. Подскажите пожалуйста, где их можно получить?

**Comment by null-z** [comment]
> Добрый день!
> 
> Устанавливаю библиотеку через Cocoapods. Установилась версия 3.5.0
> При сборке получаю ошибку **No such module 'TMXProfiling'**.
> Но таких библиотек в проекте нет. Подскажите пожалуйста, где их можно получить?

TMXProfiling и TMXProfilingConnections подключаются вручную, а получить их можно от вашего менеджера в Яндекс.Кассе.
[Тут](https://github.com/yandex-money/yandex-checkout-payments-swift#%D0%BF%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-tmxprofiling-%D0%B8-tmxprofilingconnections) описано как их подключать.
