### ISSUE TITLE
dyld: Library not loaded: @rpath/TMXProfilingConnections.framework/TMXProfilingConnections    Reason: image not found

### ISSUE THREAD

**Issue by EgorkZe** [yoomoney/yookassa-payments-swift#69]
Получаю ошибку
dyld: Library not loaded: @rpath/TMXProfilingConnections.framework/TMXProfilingConnections
  Referenced from: /private/var/containers/Bundle/Application/82C27571-503F-4838-A1C8-93B7A3FBA803/Приложение.app/Приложение
  Reason: image not found

Сделал все по инструкции, создал папку Frameworks в корне проекте, в проект закинул эти TMX фреймворки, в General все настроил. Но при запуске краш с ошибкой выше.
Если поставить Embed and Sign то все работает и на девайсе запускается, но при паблише в аппстор получаю такую ошибку Code signing "TMXProfiling.framework" failed.

**Comment by KirillovE** [comment]
Такая же ситуация. Только "Если поставить Embed and Sign" не пробовал
Что странно, приложение у меня запускается, а вот UI тесты выдают эту ошибку

**Comment by oltv00** [comment]
@EgorkZe 
подскажи, актуальная ли данная проблема ?

>Если поставить Embed and Sign то все работает и на девайсе запускается, но при паблише в аппстор получаю такую ошибку Code signing "TMXProfiling.framework" failed.

Необходимо добавить `strip_framework.sh` в `Build Phases -> New Run Script Phase`
Тогда такой проблемы не будет.

**Comment by EgorkZe** [comment]
@oltv00 Не, уже не актуальна, спасибо!
