### ISSUE TITLE
Version 4.0.0

### ISSUE THREAD

**Issue by rastaman111** [yoomoney/yookassa-payments-swift#76]
<img width="566" alt="Снимок экрана 2020-10-22 в 09 35 50" src="https://user-images.githubusercontent.com/15727518/96834078-0d683280-144a-11eb-884b-6234b42a1b71.png">

**Comment by oltv00** [comment]
В Podfile прописали новый `source` для `MoneyAuth` ?

source 'https://github.com/yandex-money-tech/cocoa-pod-specs.git'

**Comment by rastaman111** [comment]
Хм, не менял, как у прошлой версии стоит

**Comment by oltv00** [comment]
>Хм, не менял, как у прошлой версии стоит

Нужно не менять, а добавить еще один : )
[Как тут](https://github.com/yandex-money/yandex-checkout-payments-swift/blob/master/YandexCheckoutPaymentsExample/Podfile-example).

И почитайте [гайди по миграции на 4.0.0](https://github.com/yandex-money/yandex-checkout-payments-swift/blob/master/MIGRATION.md), там есть пункт специально [про этот кейс](https://github.com/yandex-money/yandex-checkout-payments-swift/blob/master/MIGRATION.md#добавить-новые-зависимости).

**Comment by rastaman111** [comment]
А все понял, думал что как всегда просто версию поменял и все дела)

**Comment by oltv00** [comment]
>А все понял, думал что как всегда просто версию поменял и все дела)

В major апдейтах так обычно не работает)
