### ISSUE TITLE
target has transitive dependencies

### ISSUE THREAD

**Issue by maslovsa** [yoomoney/yookassa-payments-swift#78]
Hi there

Faced issues while integrate you Library.
Specially created new test project

> [!] The 'Pods-TestPayments' target has transitive dependencies that include statically linked binaries: (/Users/maslovsa/Projects/Profsoft/TestPayments/Pods/MoneyAuth/MoneyAuth.xcframework)

or

> [!] An unexpected version directory `Source` was encountered for the `/Users/maslovsa/.cocoapods/repos/yoomoney/YandexCheckoutWalletApi` Pod in the `YandexCheckoutWalletApi` repository.

Test project can be find there:
https://github.com/maslovsa/TestPayments.git

My Podfile
```
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/yandex-money-tech/cocoa-pod-specs.git'

platform :ios, '10.0'
use_frameworks!

target 'TestPayments' do

  pod 'YandexCheckoutPayments',
   :git => 'https://github.com/yandex-money/yandex-checkout-payments-swift.git',
   :tag => '4.0.0'

end

```

**Comment by oltv00** [comment]
@maslovsa 
Hello!
I apologize for the long delay in answering.
How can I reproduce the issue?

What I tried:
```
➜ pod --version
1.10.0

17:41:37 in ~/Desktop
➜ g clone git@github.com:maslovsa/TestPayments.git
Cloning into 'TestPayments'...
remote: Enumerating objects: 32, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 32 (delta 4), reused 32 (delta 4), pack-reused 0
Receiving objects: 100% (32/32), 10.77 KiB | 3.59 MiB/s, done.
Resolving deltas: 100% (4/4), done.

17:41:44 in ~/Desktop
➜ cd TestPayments

17:41:48 in TestPayments on  master
➜ pod install --repo-update
Updating local specs repositories
***
Analyzing dependencies
Pre-downloading: `YandexCheckoutPayments` from `https://github.com/yandex-money/yandex-checkout-payments-swift.git`, tag `4.0.0`
Downloading dependencies
Installing FunctionalSwift (1.1.2)
Installing MoneyAuth (1.0.1)
Installing When (4.0.0)
Installing YandexCheckoutPayments (4.0.0)
Installing YandexCheckoutPaymentsApi (2.1.0)
Installing YandexCheckoutWalletApi (2.1.0)
Installing YandexMobileMetrica (3.7.1)
Installing YandexMoneyCoreApi (1.8.1)
Generating Pods project
Integrating client project
Pod installation complete! There is 1 dependency from the Podfile and 8 total pods installed.

17:45:47 in TestPayments on  master [?] took 1m 2s
```

As I can see, all dependencies works fine.
In what step in [the integration guide](https://github.com/yoomoney/yookassa-payments-swift#подключение-зависимостей) you got the error.

**Comment by yanapreobrazhenskaya** [comment]
Hello!
I set YooKassaPayments like
`pod 'YooKassaPayments',
    :git => 'https://github.com/yoomoney/yookassa-payments-swift.git',
    :tag => '5.0.0'`
and set YandexMobileMetrica like
`pod 'YandexMobileMetrica', '3.12.0'`
because I need 3.12 version only.
After that i do `pod install --repo-update` and get error
<img width="722" alt="Снимок экрана 2020-12-10 в 20 21 23" src="https://user-images.githubusercontent.com/72007307/101799174-47d67d80-3b25-11eb-93f7-3a5a7934e83c.png">

**Comment by oltv00** [comment]
We'll update YandexMobileMetrica to 3.12.0 soon.

**Comment by oltv00** [comment]
@yanapreobrazhenskaya 
Try new 5.1.0 version
https://github.com/yoomoney/yookassa-payments-swift/releases/tag/5.1.0

@maslovsa 
Are you working on the same project with @yanapreobrazhenskaya ?

**Comment by maslovsa** [comment]
@oltv00 thank you for the help. Yes, I helped @yanapreobrazhenskaya to resolve the issue
