### ISSUE TITLE
Отклонение двоичного файла App Store.

### ISSUE THREAD

**Issue by astarusdev** [yoomoney/yookassa-payments-swift#81]
11 декабря 2020 эпл реджекнули приложение по причине:
 1.6 Business: Payments - Apple Pay.
Guideline 3.1.6 - Business - Payments - Apple Pay

Your app uses Apple Pay as a purchasing mechanism but does not use Apple Pay branding and user interface elements appropriately as described in the [Apple Pay Human Interface Guidelines.](https://developer.apple.com/ios/human-interface-guidelines/technologies/apple-pay/)

Specifically, payee name is missing on Apple Pay payment sheet.

Next Steps

Before the user submits an order and the associated payment, the Apple Pay sheet displays information that you request. Be sure to request only the information that is needed to process the payment and complete the transaction.

Resources

For guidance on how to use Apple Pay button assets and payment marks in the customer purchase flow, review the [Apple Pay Human Interface Guidelines](https://developer.apple.com/ios/human-interface-guidelines/technologies/apple-pay/).

Текущая используемая версия яндекс кассы:
```ruby
pod 'YandexCheckoutPayments',
    :git => 'https://github.com/yandex-money/yandex-checkout-payments-swift.git',
    :tag => '3.7.1'
    pod 'YandexLoginSDK', :modular_headers => true
```
Проект на obj-c.
Как то можно настроить в текущей версии интерфейс по требованию apple?

**Comment by oltv00** [comment]
@astarusdev 
привет!
подскажи, решилась ли проблема ?

заинтересовала строка `Specifically, payee name is missing on Apple Pay payment sheet.`
`payee name` - в нашем кейсе, это `shopName` из `TokenizationModuleInputData` модели SDK.

При инициализации `TokenizationModuleInputData` вы проставляете `shopName` ?

**Comment by astarusdev** [comment]
> @astarusdev
> привет!
> подскажи, решилась ли проблема ?
> 
> заинтересовала строка `Specifically, payee name is missing on Apple Pay payment sheet.`
> `payee name` - в нашем кейсе, это `shopName` из `TokenizationModuleInputData` модели SDK.
> 
> При инициализации `TokenizationModuleInputData` вы проставляете `shopName` ?

Привет. 
Да и shopName проставляю и purchaseDescription тоже. Проблему по сути не решили, а просто отправили эту же сборку повторно, указав, что исправим в следующий раз.

**Comment by oltv00** [comment]
@astarusdev 
а ревью прошли, или еще ждете ?

На самом деле подобных issue я не встречал.
Возможно попался ревьюер такой.

Что добавлять еще на контракт Apple Pay я сходу не вижу, т.к. вся информация там уже присутствует.

**Comment by astarusdev** [comment]
> @astarusdev
> а ревью прошли, или еще ждете ?
> 
> На самом деле подобных issue я не встречал.
> Возможно попался ревьюер такой.
> 
> Что добавлять еще на контракт Apple Pay я сходу не вижу, т.к. вся информация там уже присутствует.

да, ревью прошли.

**Comment by rastaman111** [comment]
@oltv00 У меня было такое и у знакомых тоже, что аппл отклонял приложение из-за кассы, а при повторном релизе пропускал, возможно на какого проверяющего нарвёшься
