### ISSUE TITLE
Unable to find a specification for `YooMoneyCoreApi (~> 1.9.0)` depended upon by `YooKassaPayments`

### ISSUE THREAD

**Issue by pedrogarciyalopez** [yoomoney/yookassa-payments-swift#82]
Ошибка при установке:
<img width="782" alt="Снимок экрана 2020-12-15 в 13 42 21" src="https://user-images.githubusercontent.com/14232660/102204935-8a100e00-3edb-11eb-9985-546527dda02e.png">

В podfile, вроде как, все указал:
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/yoomoney-tech/cocoa-pod-specs.git'

plugin 'cocoapods-user-defined-build-types'

enable_user_defined_build_types!

platform :ios, '10.0'
install! 'cocoapods', :disable_input_output_paths => true

target 'repetitMobileApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  pod 'YooKassaPayments',
  :build_type => :dynamic_framework,
  :git => 'https://github.com/yoomoney/yookassa-payments-swift.git',
  :tag => '5.0.1'
      
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'repetitMobileAppTests' do
    # inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
  end
end

```

**Comment by oltv00** [comment]
@pedrogarciyalopez 
Привет!
А какая команда выполняется в консоле для установки зависимостей ?
Пробовали `pod install --repo-update` ?

**Comment by pedrogarciyalopez** [comment]
@oltv00 
Привет! У нас проект на react-native, и там команда такая: `npx pod-install`. https://github.com/expo/expo-cli/tree/master/packages/pod-install. Вещь призванная решить все проблемы вроде `pod install --repo-update` и т.п.
Странно, но она не помогла. Помогло `pod update`, правда потом пришлось ревертнуть Podfile.lock, т.к. `pod update` обновил все зависимости до последних верский, чего нам не нужно. И после этого `npx pod-install` отработал, как надо.

**Comment by oltv00** [comment]
@pedrogarciyalopez 
Довольно странно.
`pod install --repo-update` устанавливает поды, обновляя pod repo, и не меняет Podfile.lock

еще можно было попробовать сделать 
`pod repo update`
а потом просто `pod install`

эти две команды аналогичны `pod install --repo-update`
