### ISSUE TITLE
Building for iOS, but the linked and embedded framework 'TMXProfiling.framework' was built for iOS + iOS Simulator.

### ISSUE THREAD

**Issue by underqcool** [yoomoney/yookassa-payments-swift#83]
Обновились до Xcode 12.3, теперь стабильная ошибка в начале сборки проекта при любой конфигурации и схеме.

Если попробовать сменить устройство на симулятор, то ошибка меняется на _"Building for iOS Simulator, but the linked and embedded framework 'TMXProfiling.framework' was built for iOS + iOS Simulator."_

Попробовали Clean Build Folder, заново настроить TMXProfiling, не помогает, версия YooKassa 5.0.0.

**Comment by oltv00** [comment]
На текущий момент workaround это проблемы - использовать Xcode <= 12.2
Планируется релиз с решением проблемы.
По результатам вернусь сюда.

**Comment by RODIONOVCo** [comment]
@oltv00 

При откате на предыдущую версию Xcode все равно не дает выгрузить приложение в store к сожалению

**Comment by RODIONOVCo** [comment]
@oltv00 когда примерно будет решение проблемы?
Сегодня последний день перед праздниками выгрузить обновление, и надо сориентировать заказчика. Спасибо.

**Comment by oltv00** [comment]
@RODIONOVCo 
С поддержкой 12.3 к сожалению есть проблемы, которые быстро решить не удалось.
Ориентировочно - срок решения проблемы, неделя, возможно больше : (

Подскажи, а почему нужна именно версия 12.3 ?
Версия Xcode 12.2 не подходит для сборки приложения в стор ?

**Comment by RODIONOVCo** [comment]
@oltv00 совершенно верно. Пробовал залиться залиться на Xcode 12.2, в конце загрузки выдал ошибки. Скрин не сделал к сожалению. 
Могу предположить, что нужен новый фраемворк с типом . xcframework, но это не точно 😄

**Comment by oltv00** [comment]
@RODIONOVCo 
Могу предположить что ошибка которую ты видел была связана с `TMXProfiling`
Если это так - нужно проверить, выполнен ли пункт номер 4 из [инструкции по подключению](https://github.com/yoomoney/yookassa-payments-swift#подключение-tmxprofiling-и-tmxprofilingconnections)

Там нужно добавить в `Build Phases -> New Run Script Phase` файл `strip_framework.sh`
Выглядеть это должно вот так.
Чтобы точно не было проблемы - лучше этот скрипт поместить в конец `build phase`.
В самом скрипте, в его шапке, достаточно подробно написано, зачем он нужен.

![image](https://user-images.githubusercontent.com/14943414/102872485-cb12a000-4450-11eb-95d2-61d1d5876660.png)

**Comment by RODIONOVCo** [comment]
@oltv00 сейчас еще раз попробую на Xcode 12.2 и отпишусь :)

**Comment by RODIONOVCo** [comment]
@oltv00 обновился с 5.0.1 на 5.1.0, и загрузился с 12.2, все прошло без ошибок! Спасибо!

**Comment by ipolh** [comment]
с 12.3 регилась проблема?

**Comment by KirillovE** [comment]
> с 12.3 решилась проблема?

У меня нет

**Comment by oltv00** [comment]
@ipolh @KirillovE 
Задача по поддержке в SDK Xcode версии 12.3 в работе, но боюсь до праздников не успеть.
Как будет готов релиз, я напишу в этот тред.

**Comment by ipolh** [comment]
Есть новости? а то скоро китайский уже Новый год наступит. Клиенты ждут

**Comment by grafovdenis** [comment]
Пробовал много решений из StackOverflow.
[Это](https://stackoverflow.com/questions/63267897/building-for-ios-simulator-but-the-linked-framework-framework-was-built/65306886#65306886) помогло.

_Originally posted by @grafovdenis in https://github.com/yoomoney/yookassa-payments-swift/issues/84#issuecomment-766689593_

**Comment by rastaman111** [comment]
> Пробовал много решений из StackOverflow.
> 
> [Это](https://stackoverflow.com/questions/63267897/building-for-ios-simulator-but-the-linked-framework-framework-was-built/65306886#65306886) помогло.
> 
> 
> 
> _Originally posted by @grafovdenis in https://github.com/yoomoney/yookassa-payments-swift/issues/84#issuecomment-766689593_

Мне не помогло

**Comment by rastaman111** [comment]
@oltv00 Приветствую! Есть новости и какие то планы о релизе?

**Comment by grafovdenis** [comment]
> > Пробовал много решений из StackOverflow.
> > [Это](https://stackoverflow.com/questions/63267897/building-for-ios-simulator-but-the-linked-framework-framework-was-built/65306886#65306886) помогло.
> > _Originally posted by @grafovdenis in [#84 (comment)](https://github.com/yoomoney/yookassa-payments-swift/issues/84#issuecomment-766689593)_
> 
> Мне не помогло

[Это](https://stackoverflow.com/a/65307593) пробовал?

**Comment by Miha-ha** [comment]
> > > Пробовал много решений из StackOverflow.
> > > [Это](https://stackoverflow.com/questions/63267897/building-for-ios-simulator-but-the-linked-framework-framework-was-built/65306886#65306886) помогло.
> > > _Originally posted by @grafovdenis in [#84 (comment)](https://github.com/yoomoney/yookassa-payments-swift/issues/84#issuecomment-766689593)_
> > 
> > 
> > Мне не помогло
> 
> [Это](https://stackoverflow.com/a/65307593) пробовали?

Я попробовал. Теперь такая ошибка:
/Pods/YooKassaPayments/YooKassaPayments/Private/Services/Authorization/AuthorizationMediator.swift:3:8: Failed to build module 'MoneyAuth' from its module interface; the compiler that produced it, 'Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)'

Вы можете собрать XCFramework  на последнем XCode 12.4?

**Comment by rastaman111** [comment]
> > > > Пробовал много решений из StackOverflow.
> 
> > > > [Это](https://stackoverflow.com/questions/63267897/building-for-ios-simulator-but-the-linked-framework-framework-was-built/65306886#65306886) помогло.
> 
> > > > _Originally posted by @grafovdenis in [#84 (comment)](https://github.com/yoomoney/yookassa-payments-swift/issues/84#issuecomment-766689593)_
> 
> > > 
> 
> > > 
> 
> > > Мне не помогло
> 
> > 
> 
> > [Это](https://stackoverflow.com/a/65307593) пробовали?
> 
> 
> 
> Я попробовал. Теперь такая ошибка:
> 
> /Pods/YooKassaPayments/YooKassaPayments/Private/Services/Authorization/AuthorizationMediator.swift:3:8: Failed to build module 'MoneyAuth' from its module interface; the compiler that produced it, 'Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)'
> 
> 
> 
> Вы можете собрать XCFramework  на последнем XCode 12.4?

У меня вчера такая же ошибка появилась, хотя то что писали до этого помогло и проект запускался, пока информацию по этой ошибке и ее решения не нашёл, как найдёте дайте знать

**Comment by ssitdikov** [comment]
> Пробовал много решений из StackOverflow.
> [Это](https://stackoverflow.com/questions/63267897/building-for-ios-simulator-but-the-linked-framework-framework-was-built/65306886#65306886) помогло.
> 
> _Originally posted by @grafovdenis in [#84 (comment)](https://github.com/yoomoney/yookassa-payments-swift/issues/84#issuecomment-766689593)_

12.5 beta - помогает этот способ.

**Comment by rastaman111** [comment]
Мне ещё помогло поставить в подФайл 

# platform :ios, '12.0'

Так как касса от 10, а по дефолту ставится 9

**Comment by ashalaurov** [comment]
> @ipolh @KirillovE
> Задача по поддержке в SDK Xcode версии 12.3 в работе, но боюсь до праздников не успеть.
> Как будет готов релиз, я напишу в этот тред.

Есть новости?

**Comment by KirillovE** [comment]
@ashalaurov нет, до сих пор Xcode 12.2 используем

**Comment by rastaman111** [comment]
Интересно, обновление будет или как?)

**Comment by AlexGee17** [comment]
Решения проблемы до сих пор нет? Середина марта уже - ждём фикс с декабря 2020 о_О

**Comment by rastaman111** [comment]
> Решения проблемы до сих пор нет? Середина марта уже - ждём фикс с декабря 2020 о_О

Они обновили кассу, но не знаю, решена ли проблема или не.

**Comment by AlexGee17** [comment]
> > Решения проблемы до сих пор нет? Середина марта уже - ждём фикс с декабря 2020 о_О
> 
> Они обновили кассу, но не знаю, решена ли проблема или не.

Xcode 12.4 проблема не решена

**Comment by rastaman111** [comment]
> > > Решения проблемы до сих пор нет? Середина марта уже - ждём фикс с декабря 2020 о_О
> 
> > 
> 
> > Они обновили кассу, но не знаю, решена ли проблема или не.
> 
> 
> 
> Xcode 12.4 проблема не решена 

Значит не решили :)

**Comment by ask9rov** [comment]
https://stackoverflow.com/questions/63267897/building-for-ios-simulator-but-the-linked-framework-framework-was-built

**Comment by bits84** [comment]
реально, что делать то? мы даже выкатить обновление не можем

**Comment by rastaman111** [comment]
> реально, что делать то? мы даже выкатить обновление не можем

У меня получилось обнову выкатить)

**Comment by Miha-ha** [comment]
> > реально, что делать то? мы даже выкатить обновление не можем
> 
> У меня получилось обнову выкатить)

что в итоге сработало?

**Comment by rastaman111** [comment]
> > > реально, что делать то? мы даже выкатить обновление не можем
> 
> > 
> 
> > У меня получилось обнову выкатить)
> 
> 
> 
> что в итоге сработало?

Что то конкретное не могу сказать, а вот удача была

**Comment by oltv00** [comment]
Опубликовали новую версию (https://github.com/yoomoney/yookassa-payments-swift/releases/tag/5.3.0) с поддержкой Xcode 12.*
\* - 1, 2, 3, 4, etc...

Для корректной интеграции необходимо выполнить инструкцию из MIGRATION.md

```
В версии 5.3.0 зависимости `TMXProfiling` и `TMXProfilingConnections` используются в виде `.xcframework`.

Для корректной работы необходимо:
1. Запросить у менеджера по подключению зависимости `TMXProfiling.xcframework` и `TMXProfilingConnections.xcframework`
2. В разделе `General` у основного таргета проекта добавить `TMXProfiling.xcframework` и `TMXProfilingConnections.xcframework` в `Frameworks, Libraries, and Embedded Content`.
3. Удалить в `Build Phases` скрипт из файла `strip_framework.sh`.
```

**Comment by underqcool** [comment]
Удалось собрать проект на Xcode 12.4 с новыми .xcframework, issue думаю можно закрыть.

Будет интересно узнать причину проблемы и почему так долго решали, надеюсь там было что-то хардкорное, а не просто ждали перехода CI на новый Xcode.
