### ISSUE TITLE
dyld: Library not loaded: @rpath/TMXProfilingConnections.framework/TMXProfilingConnections   Referenced from: /private/var/containers/Bundle/Application/6931425E-675D-4798-8B76-497A0870296A/Tourists.app/Tourists   Reason: image not found

### ISSUE THREAD

**Issue by rastaman111** [yoomoney/yookassa-payments-swift#84]
Получаю ошибку
dyld: Library not loaded: @rpath/TMXProfilingConnections.framework/TMXProfilingConnections
Referenced from: /private/var/containers/Bundle/Application/82C27571-503F-4838-A1C8-93B7A3FBA803/Приложение.app/Приложение
Reason: image not found

После обновления до 5.0.0 начала выскакивать такая ошибка, на 4.0.0 и до нее все норм было

**Comment by RODIONOVCo** [comment]
Точно такая же ошибка. 
И при попытке добавить framework'и не дает собрать проект. Скрин ошибок прикрепляю ниже.
Появилась проблема после обновления Xcode до версии 12.3. При откате на предыдущую версию не дает выгрузить обновление.

<img width="509" alt="Снимок экрана 2020-12-17 в 18 08 18" src="https://user-images.githubusercontent.com/62603126/102505561-347e6180-4093-11eb-95d6-c8864cafe184.png">

**Comment by ipolh** [comment]
Коллеги как выкрутится из этой ситуации?
Невозможно обновлять приложение.
Очень срочно нужно решить этот вопрос

**Comment by rastaman111** [comment]
> Коллеги как выкрутится из этой ситуации?
> 
> Невозможно обновлять приложение.
> 
> Очень срочно нужно решить этот вопрос

 Такая же фигня, нужно обновить приложение и тут такая засада.

**Comment by oltv00** [comment]
Ошибки `dyld: Library not loaded` и `Building for iOS Simulator, but the linked and embedded framework 'TMXProfiling.framework' was built for iOS + iOS Simulator."` - разные.

`dyld: Library not loaded` - вероятно не выполнен пункт 2, 3, 4 из https://github.com/yoomoney/yookassa-payments-swift/blob/master/README.md#подключение-tmxprofiling-и-tmxprofilingconnections

Ошибка 'TMXProfiling.framework' was built for iOS + iOS Simulator." - обсуждается тут https://github.com/yoomoney/yookassa-payments-swift/issues/83, тут необходима доработка в нашем SDK, и сейчас ведется работа.

**Comment by oltv00** [comment]
@rastaman111 подскажи, получилось ли решить проблему с использованием версии Xcode 12.2 или ниже ?

**Comment by rastaman111** [comment]
@oltv00 
Добрый день, у меня Xcode 12.3 
Сегодня попробую установить 5.1.0 и дам ответ

**Comment by oltv00** [comment]
@rastaman111 12.3 не будет работать.
Решается эта проблема тут https://github.com/yoomoney/yookassa-payments-swift/issues/83

Пока что для подключения SDK нужно использовать 12.2 или ниже.
Если с проблема с `dyld: Library not loaded` не воспроизведется - думаю можно закрывать issue.

**Comment by rastaman111** [comment]
@oltv00 Появились примерные сроки выхода новой версии?

**Comment by oltv00** [comment]
@rastaman111 
Задача по поддержке в SDK Xcode версии 12.3 в работе, но боюсь до праздников не успеть.
Как будет готов релиз, я напишу в тред https://github.com/yoomoney/yookassa-payments-swift/issues/83
В этом треде давай решать проблему `dyld: Library not loaded` на Xcode версии 12.2 или ниже.
Если проблема решена, можно закрыть issue.

**Comment by rastaman111** [comment]
> @rastaman111 
> 
> Задача по поддержке в SDK Xcode версии 12.3 в работе, но боюсь до праздников не успеть.
> 
> Как будет готов релиз, я напишу в тред https://github.com/yoomoney/yookassa-payments-swift/issues/83
> 
> В этом треде давай решать проблему `dyld: Library not loaded` на Xcode версии 12.2 или ниже.
> 
> Если проблема решена, можно закрыть issue.

Как тут я указывал тут также проблема с 12.3, можно эту закрыть и перейти в #83

**Comment by oltv00** [comment]
> > @rastaman111 
> > 
> > Задача по поддержке в SDK Xcode версии 12.3 в работе, но боюсь до праздников не успеть.
> > 
> > Как будет готов релиз, я напишу в тред https://github.com/yoomoney/yookassa-payments-swift/issues/83
> > 
> > В этом треде давай решать проблему `dyld: Library not loaded` на Xcode версии 12.2 или ниже.
> > 
> > Если проблема решена, можно закрыть issue.
> 
> Как тут я указывал тут также проблема с 12.3, можно эту закрыть и перейти в #83

Да, давай закроем, и перейдем.

**Comment by grafovdenis** [comment]
Пробовал много решений из StackOverflow.
[Данное решение](https://stackoverflow.com/questions/63267897/building-for-ios-simulator-but-the-linked-framework-framework-was-built/65306886#65306886) помогло.

**Comment by ipolh** [comment]
пробовал не помогло
