### ISSUE TITLE
No such module 'MoneyAuth'

### ISSUE THREAD

**Issue by Lexfoxer** [yoomoney/yookassa-payments-swift#86]
При выставлении для schema "Build Configuration: Release", стала появляться ошибка `No such module 'MoneyAuth'`

Podfile имеет эти строки:
```
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/yoomoney-tech/cocoa-pod-specs.git'
plugin 'cocoapods-user-defined-build-types'
enable_user_defined_build_types!
```
...

```
  pod 'YooKassaPayments',
    :build_type => :dynamic_framework,
    :git => 'https://github.com/yoomoney/yookassa-payments-swift.git',
    :tag => '5.1.0'
```

- `use_frameworks` - не используется
- Xcode версии 12.2 (12B45b)
- Build выполняется для iPhone 11 / iOS 14.2

**Comment by Lexfoxer** [comment]
<img width="261" alt="Снимок экрана 2020-12-31 в 12 47 24" src="https://user-images.githubusercontent.com/3188592/103406844-32c19d00-4b6d-11eb-8bb0-72aa0993cb65.png">

**Comment by oltv00** [comment]
@Lexfoxer 
Привет!

Воспроизвел ошибку.
Действительно, если в Podfile будет подобная конфигурация, то при сборке на симулятор я получаю ошибку `No such module 'MoneyAuth'`

Но при сборке под архитектуру физического устройства, такой ошибки нет.

Т.е. кажется что решение такое:
- Использовать Debug конфигурацию для сборок на симулятор и физический девайс.
- Использовать Release конфигурация только для сборок на физический девайс.

Подскажи, воспроизводится ли проблема при сборке на физический девайс ?

**Comment by Lexfoxer** [comment]
При сборке на девайсе ошибка отсутствует.

Есть идеи по какой причине это происходит?

**Comment by oltv00** [comment]
@Lexfoxer
Я не уверен, но могу предположить что это происходит из за особенности работы `.xcframework`
В Release конфигурации xcframework нет поддержки архитектуры для симулятора.

**Comment by oltv00** [comment]
@Lexfoxer 
Есть еще какие то проблемы с данной проблемой ?

**Comment by Lexfoxer** [comment]
Нет, закрываем

**Comment by designervoid** [comment]
столкнулся с такой же проблемой на react native. на симуляторе ошибка при `npx pod-install`, а на девайсе запустилось.
установка `pod` в `Podfile`:
```
pod 'YooKassaPayments',
    :git => 'https://github.com/yoomoney/yookassa-payments-swift.git',
    :tag => '5.3.0
    ```
