### ISSUE TITLE
Failed to build module 'MoneyAuth' - ошибка версии Swift

### ISSUE THREAD

**Issue by kuznetsov-from-wonderland** [yoomoney/yookassa-payments-swift#87]
Выполняю переход с Яндекс.Кассы на этот SDK

Версия
```
pod 'YooKassaPayments',
    :git => 'https://github.com/yoomoney/yookassa-payments-swift.git',
    :tag => '5.1.0'
```

**XCode** Version 12.2 (12B45b)

При запуске случается ошибка
```
Failed to build module 'MoneyAuth' from its module interface; the compiler that produced it, 'Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)'
```

В настройках XCode 
![1610361055731](https://user-images.githubusercontent.com/33729094/104170214-cfa7f400-5411-11eb-8cf3-33c69cadc68b.jpg)

На рабочей машине
`swift --version`
`Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)`
`Target: x86_64-apple-darwin19.6.0`

**Comment by kuznetsov-from-wonderland** [comment]
Кажется проблема в том, что `MoneyAuth` собрана в XCode 11

**Comment by oltv00** [comment]
@kuznetsov-from-wonderland 
Привет!

В Podfile прописана настройка `use_frameworks!` ?

**Comment by kuznetsov-from-wonderland** [comment]
> @kuznetsov-from-wonderland
> Привет!
> 
> В Podfile прописана настройка `use_frameworks!` ?

Нет. У меня проект `react-native`

**Comment by kuznetsov-from-wonderland** [comment]
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/yoomoney-tech/cocoa-pod-specs.git'

platform :ios, '13.0'

install! 'cocoapods', :disable_input_output_paths => true

target 'myproject' do
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  # YOOKASSA (ex Yandex Kassa)
  pod 'MyFramework', :path => '../react-native-yandex-kassa/ios/MyFramework.podspec'
  pod 'YooKassaPayments',
    :git => 'https://github.com/yoomoney/yookassa-payments-swift.git',
    :tag => '5.1.0'

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end
```

**Comment by oltv00** [comment]
@kuznetsov-from-wonderland 
В таком случае нужно использовать plugin 'cocoapods-user-defined-build-types'
Сейчас такого в инструкции нет, т.к. решение узнали не так давно.

В соседнем issue есть пример Podfile (https://github.com/yoomoney/yookassa-payments-swift/issues/86)
https://github.com/yoomoney/yookassa-payments-swift/issues/77 - тут об этом решении узнали, там тоже есть примеры.

Попробуй посмотреть и добавить плагин, если не получится, напиши сюда еще раз, помогу разобраться.

**Comment by kuznetsov-from-wonderland** [comment]
сейчас посмотрю, спасибо. но я уже попробовал сделать откат до XCode 11.7 и возникла новая проблема, которую пока не могу решить
```
Building for iOS Simulator, but the linked and embedded framework 'TMXProfiling.framework' was built for iOS + iOS Simulator.
```
Фреймворки слинкованы и не менялись, добавлены как Embed & SIgn

**Comment by kuznetsov-from-wonderland** [comment]
Все сделал как в соседних issue (с pod deintegrate + pod install + clean build folder)

Все равно проблема, но на этот раз другая

![image](https://user-images.githubusercontent.com/33729094/104190013-831de200-542c-11eb-90c9-f625ef4c8e23.png)

**Podfile** выглядит так

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/yoomoney-tech/cocoa-pod-specs.git'
plugin 'cocoapods-user-defined-build-types'
enable_user_defined_build_types!

platform :ios, '13.0'

install! 'cocoapods', :disable_input_output_paths => true

target 'myawesomeproject' do
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  # YOOKASSA (ex Yandex Kassa)
  pod 'MyFramework', :path => '../react-native-yandex-kassa/ios/MyFramework.podspec'
  pod 'YooKassaPayments',
    :build_type => :dynamic_framework,
    :git => 'https://github.com/yoomoney/yookassa-payments-swift.git',
    :tag => '5.1.0'

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end
```

**Comment by oltv00** [comment]
@kuznetsov-from-wonderland 
а какая версия Xcode ?
Если 12.3, то на текущий момент с ней есть проблемы.

Сейчас лучше использовать 12.2

**Comment by kuznetsov-from-wonderland** [comment]
Да, была версия 12.3 - снес ее и установил 12.2
![image](https://user-images.githubusercontent.com/33729094/104199246-43f58e00-5438-11eb-813f-18ba70db8be2.png)

В итоге после дня траблшутинга все заработало, но☝️только на реальном девайсе. На симуляторе - по-прежнему не работает, а хотелось бы

Проблема выглядит так
![image](https://user-images.githubusercontent.com/33729094/104211436-21b63d00-5445-11eb-8b4e-76508cf5d24c.png)

Что я делаю не так? Возможно ли помочь? Все же коммерчески используем ваш продукт

**Comment by oltv00** [comment]
@kuznetsov-from-wonderland 
А какую схему запускаете ? Release или Debug ?
Release схема не может быть запущена на симуляторе.

**Comment by ajdos** [comment]
@oltv00 
У меня проект даже не собирается. Такие же ошибки как у @kuznetsov-from-wonderland , даже Debug сборка не работает(
Также есть такой ворнинг
![Снимок экрана 2021-01-12 в 11 57 45](https://user-images.githubusercontent.com/43725852/104292179-8e751a00-54cd-11eb-85fc-4dc2948dd51b.png)
Может ли это вызывать 36 ошибок?

**Comment by oltv00** [comment]
@ajdos лучше завести отдельный issue, и туда написать ошибку или шаги как воспроизвести.

**Comment by mikhail-timofeev-epam** [comment]
Привет, столкнулся с такой же ошибкой, повторил все шаги что были предложены, но к сожалению без результата. 
@kuznetsov-from-wonderland Как в итоге получилось решить?
Куда можно еще копнуть?

**Comment by ajdos** [comment]
@mikhail-timofeev-epam Мне помогло обновление Cocoapods. Попробуй это: https://stackoverflow.com/questions/55505991/xcode-10-2-update-issue-build-system-error-1-unable-to-load-contents-of-file-l

**Comment by ZhassulanAimukhambetov** [comment]
Такая же проблема. После миграции по инструкции выходит две ошибки.

<img width="784" alt="Снимок экрана 2021-02-12 в 16 51 07" src="https://user-images.githubusercontent.com/57430894/107759446-87525d80-6d52-11eb-8830-6b7a40ae6b25.png">
<img width="466" alt="image" src="https://user-images.githubusercontent.com/57430894/107759587-b799fc00-6d52-11eb-80ab-1bc980204b22.png">
<img width="520" alt="image" src="https://user-images.githubusercontent.com/57430894/107759634-c8e30880-6d52-11eb-930c-afb5b82fc0c8.png">
