### ISSUE TITLE
После оплаты через ApplePay не пропадает тень

### ISSUE THREAD

**Issue by Lexfoxer** [yoomoney/yookassa-payments-swift#89]
После успешной оплаты через Apple Pay не пропадает затемнение, которое появляется при выборе способа оплаты.

1. На первом скрине только создалась тень и появилась шторка выбора способа оплаты.
2. На втором заметно, что тени ApplePay и тени от шторки наложились (однако, шторка пропала после выбора способа оплаты).
3. На третьем сам баг. Шторки выбора способа оплаты нет, тень осталась, а оплата успешно выполнилась. При клике по тени ничего не происходит, работать с приложением можно только после перезапуска.

Подскажите, на чьей стороне эта проблема и как её решить?

- YooKassaPayments 5.1.0
- Xcode 12.2 (12B45b)
- Выполняется на физическом устройстве (iPhone 11 Pro / iOS 14.3)

![IMG_4945](https://user-images.githubusercontent.com/3188592/104243270-6061ec80-5471-11eb-9cf4-9eb3d531cfb7.jpg)

![IMG_4946](https://user-images.githubusercontent.com/3188592/104243393-8d160400-5471-11eb-9138-eb54841fee99.jpg)

![IMG_4947](https://user-images.githubusercontent.com/3188592/104243597-dcf4cb00-5471-11eb-9a2f-98d9d100fa95.jpg)

**Comment by oltv00** [comment]
@Lexfoxer 
Привет!

Вероятней всего проблема где то в реализации метода 
```
func tokenizationModule(
        _ module: TokenizationModuleInput,
        didTokenize token: Tokens,
        paymentMethodType: PaymentMethodType
)
```

протокола `TokenizationModuleOutput`

Там должен вызываться `dismiss(animated:)`

Пример реализации есть [тут](https://github.com/yoomoney/yookassa-payments-swift#быстрая-интеграция).
Выглядит он так:

```
func tokenizationModule(_ module: TokenizationModuleInput,
                                           didTokenize token: Tokens,
                                           paymentMethodType: PaymentMethodType) {
        DispatchQueue.main.async { [weak self] in
            guard let self = self else { return }
            self.dismiss(animated: true)
        }
        // Отправьте токен в вашу систему
}
```

Если у вас похожая реализация, то можете ее показать?

**Comment by Lexfoxer** [comment]
У меня приложение на react native.

В модуле код такой.

![15C763F9-00D9-4E47-B8EA-B8F202E2453D](https://user-images.githubusercontent.com/3188592/104286166-b95b7000-54c5-11eb-9558-953f169dcf71.jpeg)

**Comment by oltv00** [comment]
@Lexfoxer 
Сложно предположить почему так происходит.
Судя по коду, dismiss должен вызываться 100%.
Но могу предложить это проверить, например поставив breakpoint.

Если вызывается, и тень так и не пропадает, то можно попробовать (только попробовать !) вызвать dismiss 2 раза подряд.

Если тень пропадет то, можно предположить что проблема где то в вызовах dismiss до этого момента.
В таком случае мне понадобится тестовый проект, или шаги по воспроизведению проблемы, т.к. такой кейс мне не встречался ранее, и воспроизвести у меня его не получилось.

**Comment by Lexfoxer** [comment]
Вызов dismiss 2 раза решает проблему...

**Comment by Lexfoxer** [comment]
Сделал через проверку 

```swift
DispatchQueue.main.async {
    self.viewController!.dismiss(animated: true)

    if (self.viewController!.isViewLoaded && self.viewController!.view.window) {
        self.viewController!.dismiss(animated: true)
    }
}
```

Подозреваю, что это проблема в использовании react-native, так как перед отображением шторки появляются ошибки в логах:

```
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIViewController init]
PID: 29143, TID: 2872062, Thread name: (none), Queue name: com.facebook.react.ShadowQueue, QoS: 33
...
2021-01-12 14:33:11.617769+0300 appName[29143:2872062] [reports] Main Thread Checker: UI API called on a background thread: -[UIViewController init]
PID: 29143, TID: 2872062, Thread name: (none), Queue name: com.facebook.react.ShadowQueue, QoS: 33
...

=================================================================

Main Thread Checker: UI API called on a background thread: -[UIViewController initWithNibName:bundle:]
PID: 29143, TID: 2872062, Thread name: (none), Queue name: com.facebook.react.ShadowQueue, QoS: 33
...
2021-01-12 14:33:26.072667+0300 appName[29143:2872062] [reports] Main Thread Checker: UI API called on a background thread: -[UIViewController initWithNibName:bundle:]
PID: 29143, TID: 2872062, Thread name: (none), Queue name: com.facebook.react.ShadowQueue, QoS: 33
...

=================================================================
Main Thread Checker: UI API called on a background thread: -[UIViewController setTransitioningDelegate:]
PID: 29143, TID: 2872062, Thread name: (none), Queue name: com.facebook.react.ShadowQueue, QoS: 33
...
2021-01-12 14:33:26.415561+0300 appName[29143:2872062] [reports] Main Thread Checker: UI API called on a background thread: -[UIViewController setTransitioningDelegate:]
PID: 29143, TID: 2872062, Thread name: (none), Queue name: com.facebook.react.ShadowQueue, QoS: 33
...

=================================================================

Main Thread Checker: UI API called on a background thread: -[UIViewController setModalPresentationStyle:]
PID: 29143, TID: 2872062, Thread name: (none), Queue name: com.facebook.react.ShadowQueue, QoS: 33
...
2021-01-12 14:33:26.751970+0300 appName[29143:2872062] [reports] Main Thread Checker: UI API called on a background thread: -[UIViewController setModalPresentationStyle:]
PID: 29143, TID: 2872062, Thread name: (none), Queue name: com.facebook.react.ShadowQueue, QoS: 33
...

```

**Comment by oltv00** [comment]
@Lexfoxer 

>так как перед отображением шторки
>UI API called on a background thread

перед отображением шторки Apple Pay или самого SDK ?
если самого SDK, нужно обернуть этот вызов `present` в `DispatchQueue.main.async { ... }`

например

```
let viewController = TokenizationAssembly.makeModule( ... )
DispatchQueue.main.async {
    present(viewController, animated: true, completion: nil)
}
```

**Comment by Lexfoxer** [comment]
```swift
class YooKassa: RCTViewManager, TokenizationModuleOutput {
  var viewController: UIViewController?
  @objc
  func attach(
      _ map: NSDictionary,
      callbacker callback: @escaping RCTResponseSenderBlock
  ) -> Void {
    viewController = TokenizationAssembly.makeModule(
        inputData: inputData,
        moduleOutput: self
    )
    
    DispatchQueue.main.async {
        let rootViewController = UIApplication.shared.keyWindow!.rootViewController!
        rootViewController.present(self.viewController!, animated: true, completion: nil)
    }
```

**Comment by Lexfoxer** [comment]
@oltv00
Да, отображается перед выводом самого SDK.
Так и реализовано. Или я что-то не понимаю тк не являюсь разработчиком на Swift.

[Здесь](https://gist.github.com/Lexfoxer/588aec77c55f1b633e1c4dd2d8018073) код файла используемого для связи SDK и react-native.
