### ISSUE TITLE
 Undefined symbol errors

### ISSUE THREAD

**Issue by ajdos** [yoomoney/yookassa-payments-swift#90]
Недавно был осуществлен переход на YooKassaPayments c Яндекс.Касса.
Версия пода:
![Снимок экрана 2021-01-12 в 13 16 16](https://user-images.githubusercontent.com/43725852/104301180-6343f800-54d8-11eb-8c6a-5563c7187ccb.png)
При сборке проекта появляются 36 ошибок с заголовком "Undefined symbol":
![Снимок экрана 2021-01-12 в 13 17 08](https://user-images.githubusercontent.com/43725852/104301368-9dad9500-54d8-11eb-8f10-76c6d8de18db.png)
Deployment target для всех зависимостей 9.0
![Снимок экрана 2021-01-12 в 13 18 40](https://user-images.githubusercontent.com/43725852/104301506-c9307f80-54d8-11eb-8851-755524a77bd1.png)

Вот Podfile:
`source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/yoomoney-tech/cocoa-pod-specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'MyProject' do
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

pod 'Alamofire', '~> 4.7'
pod 'AlamofireNetworkActivityLogger','2.4.0'
pod 'RealmSwift', '~> 3.17.0'
pod 'AKMaskField', '2.0.3'
pod 'SDWebImage', '5.3.0'
pod 'YandexMapKit', '3.4'
pod 'RSBarcodes_Swift', '~> 5.0.2'

pod 'Fabric', '~> 1.10.2'
pod 'Firebase/Auth', '6.12.0'
pod 'Firebase/Messaging', '6.12.0'

pod 'ClusterKit', '0.4.1'
pod 'RxSwift', '~> 5'
pod 'RxCocoa', '~> 5'
pod 'RxAlamofire', '5.1.0'
pod 'RxGesture'
pod 'R.swift', '5.1.0'
pod 'Reusable', '4.1.0'
pod 'SnapKit'
pod 'DropDown'

pod 'IQKeyboardManagerSwift'
pod 'SwiftGifOrigin'
pod 'CardIO'
pod 'YooKassaPayments',
    :git => 'https://github.com/yoomoney/yookassa-payments-swift.git',
    :tag => '5.1.0'

pod 'PullUpController'
pod 'NVActivityIndicatorView'
pod 'RangeSeekSlider'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['AKMaskField'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    end
  end
end
`
Не знаю поможет или нет, в логах также пишет это:
![Снимок экрана 2021-01-12 в 13 21 23](https://user-images.githubusercontent.com/43725852/104302100-72777580-54d9-11eb-891c-53e62edc9adf.png)
![Снимок экрана 2021-01-12 в 13 21 46](https://user-images.githubusercontent.com/43725852/104302117-76a39300-54d9-11eb-9282-6950d69a46c2.png)
![Снимок экрана 2021-01-12 в 13 21 59](https://user-images.githubusercontent.com/43725852/104302138-7b684700-54d9-11eb-873d-b0be55ff5c7f.png)
![Снимок экрана 2021-01-12 в 13 22 10](https://user-images.githubusercontent.com/43725852/104302152-7f946480-54d9-11eb-9d71-cdf63d063790.png)
![Снимок экрана 2021-01-12 в 13 22 40](https://user-images.githubusercontent.com/43725852/104302161-8327eb80-54d9-11eb-804c-c042dee6d031.png)

**Comment by oltv00** [comment]
@ajdos 
Привет.

По логу не очень понятно где ошибка.
Подскажите версии environment: Ruby, CocoaPods, Xcode.

Для работы *.xcframework версия CocoaPods должна быть 1.10.*

**Comment by ajdos** [comment]
@oltv00 Да, действительно проблема оказалась в версии Cocoapods. Решил с помощью: https://stackoverflow.com/questions/55505991/xcode-10-2-update-issue-build-system-error-1-unable-to-load-contents-of-file-l
