### ISSUE TITLE
No such module 'YandexMobileMetrica'

### ISSUE THREAD

**Issue by dimzhurwork** [yoomoney/yookassa-payments-swift#92]
На сборке проекта выпадает error: no such module 'YandexMobileMetrica'
import YandexMobileMetrica

https://github.com/yoomoney/yookassa-payments-swift/blob/master/YooKassaPayments/Private/Services/Analytics/AnalyticsService.swift

тут есть  import YandexMobileMetrica
но в Podfile нет зависимости pod 'YandexMobileMetrica'

**Comment by novikows** [comment]
same

**Comment by starxor** [comment]
Зависимость YandexMobileMetrica описана в podspec файле библиотеки. Ожидается что pod install установит зависимость.

**Comment by dimzhurwork** [comment]
нашел в чем проблемма, если есть отдельно в основном поде зависимость яндексметрики - вылазет эта ошибка
