### ISSUE TITLE
Failed to build module 'MoneyAuth' + Compiling for iOS 10.0, but module 'FunctionalSwift'

### ISSUE THREAD

**Issue by ZhassulanAimukhambetov** [yoomoney/yookassa-payments-swift#93]
Добрый день, коллеги.
Делаю миграцию с версии 3.7.1 -> на версию 5.1.0.
Полностью пошагово согласно [инструкции](https://github.com/yoomoney/yookassa-payments-swift/blob/master/MIGRATION.md).
Добавил в podfile:

<img width="421" alt="image" src="https://user-images.githubusercontent.com/57430894/107761451-9555ad80-6d55-11eb-8f81-74a25f18161e.png">

Сейчас podfile выглядит:
<img width="513" alt="image" src="https://user-images.githubusercontent.com/57430894/107761188-27a98180-6d55-11eb-8d6e-2b8efe71db21.png">

После установки подов + чистки проекта выходят ошибки:

<img width="918" alt="image" src="https://user-images.githubusercontent.com/57430894/107761267-490a6d80-6d55-11eb-8d81-e8e04be0c5cc.png">

Xcode:

<img width="518" alt="image" src="https://user-images.githubusercontent.com/57430894/107761343-6808ff80-6d55-11eb-8b14-3726b3233ee2.png">

Советы с соседней [ветки](https://github.com/yoomoney/yookassa-payments-swift/issues/87) попробовал все. Ничего не помогло.

Жду скорой обратной связи по данной ошибке, так как мы коммерчески используем вашу библиотеку.
Заранее благодарю.

**Comment by oltv00** [comment]
@ZhassulanAimukhambetov
вероятно в `Podfile`, в `post_install` шаге устанавливается `IPHONEOS_DEPLOYMENT_TARGET` версии 11.0

попробуйте изменить код в шаге на примерно такой:
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == 'FunctionalSwift' || target.name == 'YooMoneyCoreApi'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      else
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
```

**Comment by ZhassulanAimukhambetov** [comment]
Да, получилось. Спасибо большое!
