### ISSUE TITLE
Apple Pay нет в списке платежных методов

### ISSUE THREAD

**Issue by Cigan12** [yoomoney/yookassa-payments-swift#99]
Включил Apple Pay в XCode, сертификат одобрили, но Apple pay все равно нет в списке доступных методов оплаты, ни в симуляторе, ни в TestFlight на реальных устройствах, подскажите в чем может быть проблема? Проект на react native.
Добавляю вот так
<img width="448" alt="Снимок экрана 2021-02-27 в 22 42 33" src="https://user-images.githubusercontent.com/42859813/109392152-33986480-794d-11eb-88aa-7e1791c4dad4.png">

В TokenizationModuleInputData applePayMerchantIdentifier указал

**Comment by Cigan12** [comment]
Может быть это связано с тем, что мы выпустили неверный сертификат? 
<img width="770" alt="Снимок экрана 2021-02-27 в 22 48 46" src="https://user-images.githubusercontent.com/42859813/109392330-0a2c0880-794e-11eb-8a85-7b34b64df946.png">
Какой из этих двух нужен? Мы выпускали первый)

**Comment by oltv00** [comment]
@Cigan12 

Привет!

Сертификат верный.

Есть 2 кейса которые необходимо проверить.
1. Что нет ошибки на стороне клиента, в процессе интеграции SDK.
2. Что нет ошибки на стороне сервера и БД.

**По 1 пунку,** нужно посмотреть что в модель `TokenizationModuleInputData` передается параметр `applePayMerchantIdentifier`. 

![image](https://user-images.githubusercontent.com/14943414/109777762-1f868880-7c15-11eb-8702-6c3706d366f4.png)

В Xcode он выбирается тут.

![image](https://user-images.githubusercontent.com/14943414/109777491-d5050c00-7c14-11eb-802e-af6796785d35.png)

**По 2 пункту**, нужно передать в модель `TokenizationModuleInputData`, параметр `isLoggingEnabled: true` и посмотреть логи.
Интересует запрос `https://sdk.yookassa.ru/api/frontend/v3/payment_options?amount=&currency="`
Пришлите логи сюда, или посмотрите, есть ли в списке `items` модель с `payment_method_type = apple_pay`

Если ее нет, вероятно необходимо обратиться к менеджеру по подключению и уточнить, почему может быть так.

**Comment by Cigan12** [comment]
Привет, спасибо за ответ, applePayMerchantIdentifier был) а вот такой модели нет( payment_method_type = apple_pay 
<img width="365" alt="Снимок экрана 2021-03-03 в 16 19 21" src="https://user-images.githubusercontent.com/42859813/109783354-7ce20000-7c3c-11eb-9aea-9235f5be1e06.png">

Видимо придется все таки решать эту проблему с менеджером)

**Comment by oltv00** [comment]
@Cigan12
>moneyAuthClientId это необходимая опция для apple pay? У меня нет)

`moneyAuthClientId` для Apple Pay не нужен.

>Видимо придется все таки решать эту проблему с менеджером)

Я передал в нашу поддержку этот кейс, должны починить, но вы тоже лучше напишите им.

**Comment by Cigan12** [comment]
Спасибо) Я им написал)
